# Generated by Django 5.2 on 2025-05-07 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='helper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_received', to='users.profile'),
        ),
        migrations.AddField(
            model_name='match',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_sent', to='users.profile'),
        ),
        migrations.AddField(
            model_name='match',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('seeker', 'helper', 'skill')},
        ),
    ]
